using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Million.Domain.Enitities
{
    /// <summary>
    /// Represents a property image entity in the database.
    /// </summary>
    public class PropertyImage
    {
        /// <summary>
        /// Gets or sets the unique identifier for the property image.
        /// This value is auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPropertyImage { get; set; }

        /// <summary>
        /// Gets or sets the file data for the property image.
        /// This is stored as a byte array.
        /// </summary>
        public byte[] File { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the property image is enabled.
        /// Default value is true, indicating that the image is enabled.
        /// </summary>
        public bool Enabled { get; set; } = true;

        /// <summary>
        /// Gets or sets the ID of the associated property.
        /// This is a foreign key referencing the <see cref="Property"/> class.
        /// </summary>
        public int IdProperty { get; set; }

        /// <summary>
        /// Navigation property for the associated property.
        /// </summary>
        public virtual Property Property { get; set; }
    }
}
